# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: prod

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag_created_job:
    runs-on: ubuntu-latest
    name: Deploy to Production environment
    steps:
    - uses: actions/checkout@v2
    - name: Run the Circle CI Release build
      id: curl-circle-ci
      uses: Open-Source-Contrib/circle-ci-trigger-action@latest
      with:
        circle_ci_token: ${{ secrets.CIRCLE_CI_TOKEN }}
        circle_ci_job: ${{ secrets.CIRCLE_CI_RELEASE_JOB }}
        circle_ci_project_url: ${{ github.ref }}
    # Use the output from the `webhook` step
    - name: Get the output response
      run: echo "The response was ${{ steps.curl-circle-ci.outputs.response }}"
